version: "3.8"

services:
  web:
    build: .
    container_name: gearhub-web
    ports:
      - "8090:80"
    volumes:
      - .:/usr/share/nginx/html
    networks:
      - web-network

networks:
  web-network:
    driver: bridge
